### ISSUE TITLE
Provide Mocks for ViewController on NavController and vice versa

### ISSUE THREAD

**Issue by stonelasley** [stonelasley/ionic-mocks#29]
See https://github.com/stonelasley/ionic-mocks/issues/20 for details, I had created a circular reference between Nav and ViewControllerMocks.

**Comment by enstain** [comment]
I have already covered it in my PR https://github.com/stonelasley/ionic-mocks/pull/26/commits/c6c5434cf9251a34d70226c42e82dce93c45f9a9

**Comment by stonelasley** [comment]
@enstain I don't think the private static instance fully covers this. I created this over on typescript playground but it says it's too large to share? Let me know if this doesn't replicate things correctly. 

```typescript
class Greeter {
    private static staticInstance: any = null;

    public static instance(): any {
        if (Greeter.staticInstance !== null) {
            return Greeter.staticInstance;
        }

        let i: any = {
            other: OtherGreeter.instance()
        };

        Greeter.staticInstance = i;
        return Greeter.instance();
    }

}

class OtherGreeter {
    private static staticInstance: any = null;

    public static instance(): any {
        if (OtherGreeter.staticInstance !== null) {
            return OtherGreeter.staticInstance;
        }

        let i: any = {
            greeter: Greeter.instance()
        }

        OtherGreeter.staticInstance = i;
        return OtherGreeter.instance();
    }
}

try {
    let myGreeter = Greeter.instance();
} catch (err) {
    alert(err);
}`

**Comment by stonelasley** [comment]
I have a hack in place but I'm duplicating the NavController instance method on the ViewController but the NavController that's returned doesn't have yet another ViewController. It's ugly but it should prevent current tests from breaking.

**Comment by stonelasley** [comment]
@rvdleun adding you to the conversation as you've worked on this as well.

**Comment by enstain** [comment]
I investigate ionic source a little bit just to check if they have the same problem with circular reference, so in summary: they don't. 

ViewController has a direct reference to NavController instance:
https://github.com/ionic-team/ionic/blob/master/src/navigation/view-controller.ts#L45

But NavController contains an empty array of ViewControllers on init:
https://github.com/ionic-team/ionic/blob/master/src/navigation/nav-controller-base.ts#L64

So I guess all methods which are operating with ViewController might return null if we have NavController instance "in void". Anyway, this is a right sequence of steps in ionic, as I understand it right now: we create NavController first (it doesn't have bad references), then we create ViewController and attach NavController instance to it, then we can push current ViewController into NavController views array.

I see two ways to solve this: mimic ionic behaviour further for ionic-mocks or make more workaround solutions like "fake" NavControllerMock instance inside ViewControllerMock. Since the right case is that NavController could contain several views, we might reconsider using static instance of ViewController at least.

**Comment by stonelasley** [comment]
@enstain you're correct that ionic does not have the issue because ionic is using instances as opposed to statics. I'm closing this for now as I think the way forward is to rework the project to not use statics, but that's a big lift.
